<?xml version="1.0" encoding="utf-8"?>
<Database Name="DevCamp" Class="DevCampDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=DevCamp;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DevCampConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Vote" Member="Votes">
    <Type Name="Vote">
      <Column Name="QuestionID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Vote" Member="Vote1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Question_Vote" Member="Question" ThisKey="QuestionID" OtherKey="QuestionID" Type="Question" IsForeignKey="true" />
      <Association Name="User_Vote" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Question" Member="Questions">
    <Type Name="Question">
      <Column Name="QuestionID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Question_Vote" Member="Votes" ThisKey="QuestionID" OtherKey="QuestionID" Type="Vote" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="User_Vote" Member="Votes" ThisKey="UserID" OtherKey="UserID" Type="Vote" />
    </Type>
  </Table>
</Database>